version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: MusicCompDB
      MYSQL_USER: milo
      MYSQL_PASSWORD: milo123
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  couchdb:
    image: docker.io/bitnami/couchdb:3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=couchdb
    ports:
      - '5984:5984'
    volumes:
      - CouchDB_data:/bitnami/couchdb

  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra1-data:/var/lib/cassandra
      - ./config/cassandra.yaml:/etc/cassandra/cassandra.yaml
    networks:
      - cassandra-network

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra2-data:/var/lib/cassandra
      - ./config/cassandra2.yaml:/etc/cassandra/cassandra.yaml
    networks:
      - cassandra-network

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra3-data:/var/lib/cassandra
      - ./config/cassandra3.yaml:/etc/cassandra/cassandra.yaml
    networks:
      - cassandra-network

networks:
  cassandra-network:
    driver: bridge
volumes:
  CouchDB_data:
    driver: local
  cassandra1-data:
  cassandra2-data:
  cassandra3-data: